// <auto-generated />
using System;
using Digital.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Digital.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527054414_AddEmployeeRequiredRules")]
    partial class AddEmployeeRequiredRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Digital.Api.Models.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BankName = "STATE BANK OF INDIA",
                            CreatedAt = new DateTime(2026, 5, 27, 5, 44, 13, 607, DateTimeKind.Utc).AddTicks(9458),
                            Description = "SBI"
                        },
                        new
                        {
                            Id = 2,
                            BankName = "HDFC BANK",
                            CreatedAt = new DateTime(2026, 5, 27, 5, 44, 13, 608, DateTimeKind.Utc).AddTicks(166),
                            Description = "HDFC"
                        },
                        new
                        {
                            Id = 3,
                            BankName = "ICICI BANK",
                            CreatedAt = new DateTime(2026, 5, 27, 5, 44, 13, 608, DateTimeKind.Utc).AddTicks(168),
                            Description = "ICICI"
                        },
                        new
                        {
                            Id = 4,
                            BankName = "CANARA BANK",
                            CreatedAt = new DateTime(2026, 5, 27, 5, 44, 13, 608, DateTimeKind.Utc).AddTicks(169),
                            Description = "CANARA"
                        });
                });

            modelBuilder.Entity("Digital.Api.Models.BankDetail", b =>
                {
                    b.Property<string>("EmpId")
                        .HasColumnType("text");

                    b.Property<string>("AccountHolder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IfscCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MicrCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SwiftCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmpId");

                    b.ToTable("BankDetails");
                });

            modelBuilder.Entity("Digital.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Digital.Api.Models.CompanyGst", b =>
                {
                    b.Property<string>("GstNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompanyEstablished")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DealsIn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FooterPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GstStateCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GstType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeaderPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PanNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondaryMobileNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TanNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GstNumber");

                    b.ToTable("CompanyGsts");

                    b.HasData(
                        new
                        {
                            GstNumber = "27AADCD1234A1Z1",
                            City = "",
                            Color = "",
                            CompanyAddress = "",
                            CompanyName = "DIGITAL NEW ENTERPRISES",
                            CreatedAt = new DateTime(2026, 5, 27, 5, 44, 13, 607, DateTimeKind.Utc).AddTicks(6886),
                            DealsIn = "",
                            Email = "contact@digital.com",
                            FooterPath = "",
                            GstStateCode = "",
                            GstType = "GST",
                            HeaderPath = "",
                            LogoPath = "",
                            MobileNumber = "9876543210",
                            PanNumber = "",
                            PinCode = "",
                            Remarks = "",
                            SecondaryMobileNo = "",
                            StateName = "Maharashtra",
                            TanNumber = ""
                        },
                        new
                        {
                            GstNumber = "27BBBDD4321B1Z2",
                            City = "",
                            Color = "",
                            CompanyAddress = "",
                            CompanyName = "TECH SOLUTIONS LTD",
                            CreatedAt = new DateTime(2026, 5, 27, 5, 44, 13, 607, DateTimeKind.Utc).AddTicks(8273),
                            DealsIn = "",
                            Email = "info@techsolutions.com",
                            FooterPath = "",
                            GstStateCode = "",
                            GstType = "GST",
                            HeaderPath = "",
                            LogoPath = "",
                            MobileNumber = "9988776655",
                            PanNumber = "",
                            PinCode = "",
                            Remarks = "",
                            SecondaryMobileNo = "",
                            StateName = "Karnataka",
                            TanNumber = ""
                        },
                        new
                        {
                            GstNumber = "27CCCCD9999C1Z3",
                            City = "",
                            Color = "",
                            CompanyAddress = "",
                            CompanyName = "GLOBAL LOGISTICS CORP",
                            CreatedAt = new DateTime(2026, 5, 27, 5, 44, 13, 607, DateTimeKind.Utc).AddTicks(8276),
                            DealsIn = "",
                            Email = "support@global.com",
                            FooterPath = "",
                            GstStateCode = "",
                            GstType = "GST",
                            HeaderPath = "",
                            LogoPath = "",
                            MobileNumber = "9123456789",
                            PanNumber = "",
                            PinCode = "",
                            Remarks = "",
                            SecondaryMobileNo = "",
                            StateName = "Gujarat",
                            TanNumber = ""
                        });
                });

            modelBuilder.Entity("Digital.Api.Models.DeliveryDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DeliveryDetails");
                });

            modelBuilder.Entity("Digital.Api.Models.Denomination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Denominations");
                });

            modelBuilder.Entity("Digital.Api.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyGstNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CompanyGstNumber");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyGstNumber = "27AADCD1234A1Z1",
                            CreatedAt = new DateTime(2025, 12, 22, 5, 57, 0, 0, DateTimeKind.Utc),
                            Description = "DSEC",
                            Name = "HR",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            CompanyGstNumber = "27AADCD1234A1Z1",
                            CreatedAt = new DateTime(2025, 12, 22, 5, 57, 0, 0, DateTimeKind.Utc),
                            Description = "DSEC",
                            Name = "IT",
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            CompanyGstNumber = "27AADCD1234A1Z1",
                            CreatedAt = new DateTime(2025, 12, 22, 5, 58, 0, 0, DateTimeKind.Utc),
                            Description = "DESCRIPTION",
                            Name = "SALES",
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            CompanyGstNumber = "27AADCD1234A1Z1",
                            CreatedAt = new DateTime(2025, 12, 22, 5, 58, 0, 0, DateTimeKind.Utc),
                            Description = "RESEARCH AND DEVELOPMENT",
                            Name = "R & D",
                            Status = true
                        },
                        new
                        {
                            Id = 5,
                            CompanyGstNumber = "27AADCD1234A1Z1",
                            CreatedAt = new DateTime(2025, 12, 22, 5, 59, 0, 0, DateTimeKind.Utc),
                            Description = "PLANNING AND PRODUCTION",
                            Name = "P & P",
                            Status = true
                        },
                        new
                        {
                            Id = 6,
                            CompanyGstNumber = "27AADCD1234A1Z1",
                            CreatedAt = new DateTime(2025, 12, 22, 5, 59, 0, 0, DateTimeKind.Utc),
                            Description = "ACCOUNTS",
                            Name = "ACCOUNTS",
                            Status = true
                        },
                        new
                        {
                            Id = 7,
                            CompanyGstNumber = "27AADCD1234A1Z1",
                            CreatedAt = new DateTime(2026, 4, 4, 23, 32, 0, 0, DateTimeKind.Utc),
                            Description = "CIVIL WORK",
                            Name = "CIVIL DEPARTMENT",
                            Status = true
                        });
                });

            modelBuilder.Entity("Digital.Api.Models.DesignationOfficer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("DesignationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OfficerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OfficerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("DesignationOfficers");
                });

            modelBuilder.Entity("Digital.Api.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubSubCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Digital.Api.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AadharNumber")
                        .HasColumnType("text");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("text");

                    b.Property<string>("AccountType")
                        .HasColumnType("text");

                    b.Property<string>("AlternateNumber")
                        .HasColumnType("text");

                    b.Property<string>("AnnualSalary")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .HasColumnType("text");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("text");

                    b.Property<string>("BranchName")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CurrentAddress")
                        .HasColumnType("text");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("text");

                    b.Property<string>("DateOfJoining")
                        .HasColumnType("text");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<int?>("DesignationOfficerId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactPhone")
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactRelation")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("text");

                    b.Property<string>("EsicNumber")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("IfscCode")
                        .HasColumnType("text");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NomineeDOB")
                        .HasColumnType("text");

                    b.Property<string>("NomineeName")
                        .HasColumnType("text");

                    b.Property<string>("NomineeRelation")
                        .HasColumnType("text");

                    b.Property<string>("PanNumber")
                        .HasColumnType("text");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("text");

                    b.Property<string>("PassportValidUpto")
                        .HasColumnType("text");

                    b.Property<string>("PermanentAddress")
                        .HasColumnType("text");

                    b.Property<string>("PvcNumber")
                        .HasColumnType("text");

                    b.Property<string>("PvcValidUpto")
                        .HasColumnType("text");

                    b.Property<string>("Qualification")
                        .HasColumnType("text");

                    b.Property<string>("Religion")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemporaryPassword")
                        .HasColumnType("text");

                    b.Property<string>("UanNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DesignationOfficerId");

                    b.HasIndex("LocationId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2026, 3, 31, 13, 2, 0, 0, DateTimeKind.Utc),
                            Email = "ranjan.yadav@digital.com",
                            EmployeeId = "DEE010126115",
                            LocationId = 1,
                            Name = "RANJAN YADAV",
                            Role = "Location Head",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2025, 12, 30, 6, 40, 15, 0, DateTimeKind.Utc),
                            Email = "anupam.kumar@digital.com",
                            EmployeeId = "DEE251225102",
                            LocationId = 3,
                            Name = "ANUPAM KUMAR",
                            Role = "Location Head",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 26, 42, 0, DateTimeKind.Utc),
                            Email = "sanjay.mahato@digital.com",
                            EmployeeId = "DEE251225103",
                            LocationId = 5,
                            Name = "SANJAY KUMAR MAHATO",
                            Role = "Location Head",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("Digital.Api.Models.EmployeeFamilyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("text");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("MealType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Relation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeFamilyMembers");
                });

            modelBuilder.Entity("Digital.Api.Models.EmployeeFund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GivenDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RefNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeFunds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 15000.00m,
                            CreatedAt = new DateTime(2026, 4, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            GivenDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Purpose = "Office Supplies & Development Kit Reimbursement",
                            RecordedBy = "AMANTU",
                            RefNo = "FT-948274",
                            Status = "Approved"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 8500.00m,
                            CreatedAt = new DateTime(2026, 5, 10, 11, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 3,
                            GivenDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Purpose = "Client Site Travel & Accommodation Allowance",
                            RecordedBy = "AMANTU",
                            RefNo = "FT-201847",
                            Status = "Released"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 12000.00m,
                            CreatedAt = new DateTime(2026, 5, 18, 14, 15, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 102,
                            GivenDate = new DateTime(2026, 5, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Purpose = "Technical Certification Fee Reimbursement",
                            RecordedBy = "AMANTU",
                            RefNo = "FT-583921",
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("Digital.Api.Models.EmployeeProfileUpdateRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ProfileUpdateRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            FieldName = "Role",
                            NewValue = "SENIOR ENGINEER",
                            OldValue = "JUNIOR ENGINEER",
                            RequestedAt = new DateTime(2026, 5, 19, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 3,
                            FieldName = "Qualification",
                            NewValue = "B.Tech Civil Engineering",
                            RequestedAt = new DateTime(2026, 5, 20, 11, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 102,
                            FieldName = "Email",
                            NewValue = "a.kumar@digital.com",
                            OldValue = "anupam.kumar@digital.com",
                            RequestedAt = new DateTime(2026, 5, 21, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("Digital.Api.Models.EmployeeRequiredRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AadharNumber")
                        .HasColumnType("boolean");

                    b.Property<bool>("AlternateNumber")
                        .HasColumnType("boolean");

                    b.Property<bool>("AnnualSalary")
                        .HasColumnType("boolean");

                    b.Property<bool>("BankDetails")
                        .HasColumnType("boolean");

                    b.Property<bool>("BloodGroup")
                        .HasColumnType("boolean");

                    b.Property<bool>("Category")
                        .HasColumnType("boolean");

                    b.Property<bool>("CoreQualification")
                        .HasColumnType("boolean");

                    b.Property<bool>("EmployeeCode")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsicNumber")
                        .HasColumnType("boolean");

                    b.Property<bool>("Location")
                        .HasColumnType("boolean");

                    b.Property<bool>("NomineeDetails")
                        .HasColumnType("boolean");

                    b.Property<bool>("PanNumber")
                        .HasColumnType("boolean");

                    b.Property<bool>("PassportNumber")
                        .HasColumnType("boolean");

                    b.Property<bool>("PvcNumber")
                        .HasColumnType("boolean");

                    b.Property<bool>("Religion")
                        .HasColumnType("boolean");

                    b.Property<bool>("Remarks")
                        .HasColumnType("boolean");

                    b.Property<bool>("UanNumber")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("EmployeeRequiredRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AadharNumber = true,
                            AlternateNumber = false,
                            AnnualSalary = false,
                            BankDetails = true,
                            BloodGroup = true,
                            Category = true,
                            CoreQualification = true,
                            EmployeeCode = false,
                            EsicNumber = false,
                            Location = false,
                            NomineeDetails = false,
                            PanNumber = true,
                            PassportNumber = false,
                            PvcNumber = false,
                            Religion = false,
                            Remarks = false,
                            UanNumber = false
                        });
                });

            modelBuilder.Entity("Digital.Api.Models.HsnCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HsnCodes");
                });

            modelBuilder.Entity("Digital.Api.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 19, 11, 0, 18, 0, DateTimeKind.Utc),
                            Description = "Main Office Location",
                            Name = "VISAKHAPATNAM"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 24, 2, 42, 58, 0, DateTimeKind.Utc),
                            Description = "DESC",
                            Name = "KARWAR"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 30, 6, 40, 15, 0, DateTimeKind.Utc),
                            Description = "MUMBAI",
                            Name = "MUMBAI"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 2, 6, 1, 30, 0, DateTimeKind.Utc),
                            Description = "WEST BENGAL",
                            Name = "KOLKATA"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 26, 42, 0, DateTimeKind.Utc),
                            Description = "JAMNAGAR",
                            Name = "JAMNAGAR"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 28, 28, 0, DateTimeKind.Utc),
                            Description = "KOCHIN",
                            Name = "KOCHIN"
                        });
                });

            modelBuilder.Entity("Digital.Api.Models.LocationHead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("LocationHeads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedAt = new DateTime(2026, 3, 31, 13, 2, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 101,
                            LocationId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssignedAt = new DateTime(2026, 4, 1, 4, 39, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 102,
                            LocationId = 3
                        },
                        new
                        {
                            Id = 3,
                            AssignedAt = new DateTime(2026, 4, 1, 4, 39, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 102,
                            LocationId = 2
                        },
                        new
                        {
                            Id = 4,
                            AssignedAt = new DateTime(2026, 4, 3, 4, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 103,
                            LocationId = 5
                        },
                        new
                        {
                            Id = 5,
                            AssignedAt = new DateTime(2026, 4, 3, 4, 15, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 101,
                            LocationId = 4
                        });
                });

            modelBuilder.Entity("Digital.Api.Models.MasterData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GstStateCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("MasterData");
                });

            modelBuilder.Entity("Digital.Api.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Dept")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Wing")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Dept = "P & P",
                            Desc = "DEVELOPER",
                            GroupId = 12,
                            GroupName = "JUNIOR ENGINEER",
                            Title = "SOFTWARE DEVELOPER3",
                            Wing = "ELECTRICAL"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Dept = "P & P",
                            Desc = "Welder",
                            GroupId = 15,
                            GroupName = "TECHNICIAN",
                            Title = "Welder",
                            Wing = "CIVIL"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Dept = "P & P",
                            Desc = "DEE HQ OFFICE ADMINISTRATOR",
                            GroupId = 14,
                            GroupName = "ASSISTANT SUPERVISOR",
                            Title = "DEE HQ OFFICE ADMINISTRATOR",
                            Wing = "ELECTRICAL"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Dept = "P & P",
                            Desc = "ELECTRICAL TECHNICIAN",
                            GroupId = 15,
                            GroupName = "TECHNICIAN",
                            Title = "ELECTRICAL TECHNICIAN",
                            Wing = "ELECTRICAL"
                        });
                });

            modelBuilder.Entity("Digital.Api.Models.PostGrouping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("PostGroupings");
                });

            modelBuilder.Entity("Digital.Api.Models.PostGroupingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PostGroupingId")
                        .HasColumnType("integer");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostGroupingId");

                    b.HasIndex("PostId");

                    b.ToTable("PostGroupingItems");
                });

            modelBuilder.Entity("Digital.Api.Models.Project", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("text");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Post")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Wing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Digital.Api.Models.PurchaseInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountExclGst")
                        .HasColumnType("numeric");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpenseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InvoiceFilePath")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("PanCard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RoundOff")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalCgst")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalIgst")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalSgst")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("PurchaseInvoices");
                });

            modelBuilder.Entity("Digital.Api.Models.PurchaseInvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Capacity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Cgst")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CostRate")
                        .HasColumnType("numeric");

                    b.Property<string>("Denom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Hsn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Igst")
                        .HasColumnType("numeric");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Mrp")
                        .HasColumnType("numeric");

                    b.Property<int>("PurchaseInvoiceId")
                        .HasColumnType("integer");

                    b.Property<string>("PurchaseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("SerialNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Sgst")
                        .HasColumnType("numeric");

                    b.Property<string>("Subcategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseInvoiceId");

                    b.ToTable("PurchaseInvoiceItems");
                });

            modelBuilder.Entity("Digital.Api.Models.Quotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountExclGst")
                        .HasColumnType("numeric");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryDays")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpenseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GstType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("InquiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InquiryNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Post")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuotationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RoundOff")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalCgst")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalIgst")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalSgst")
                        .HasColumnType("numeric");

                    b.Property<string>("ValidityDays")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WarrantyDays")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Wing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Quotations");
                });

            modelBuilder.Entity("Digital.Api.Models.QuotationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Capacity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Cgst")
                        .HasColumnType("numeric");

                    b.Property<string>("Denom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hsn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Igst")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("QuotationId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Sgst")
                        .HasColumnType("numeric");

                    b.Property<string>("Subcategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId");

                    b.ToTable("QuotationItems");
                });

            modelBuilder.Entity("Digital.Api.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Full system access",
                            DisplayName = "Administrator",
                            Name = "admin",
                            Permissions = ""
                        },
                        new
                        {
                            Id = 2,
                            Description = "ADMIN",
                            DisplayName = "DIRECTOR",
                            Name = "DIRECTOR",
                            Permissions = ""
                        },
                        new
                        {
                            Id = 3,
                            Description = "DESC",
                            DisplayName = "MANAGING DIRECTOR",
                            Name = "MANAGING DIRECTOR",
                            Permissions = ""
                        },
                        new
                        {
                            Id = 4,
                            Description = "HR",
                            DisplayName = "HR",
                            Name = "HR",
                            Permissions = ""
                        },
                        new
                        {
                            Id = 5,
                            Description = "IT DEPARTMENT",
                            DisplayName = "IT",
                            Name = "IT",
                            Permissions = ""
                        },
                        new
                        {
                            Id = 6,
                            Description = "DESCRIPTION",
                            DisplayName = "SENIOR MANAGER",
                            Name = "SENIOR MANAGER",
                            Permissions = ""
                        },
                        new
                        {
                            Id = 7,
                            Description = "DESCRIPTION",
                            DisplayName = "MANAGER",
                            Name = "MANAGER",
                            Permissions = ""
                        },
                        new
                        {
                            Id = 8,
                            Description = "DESCRIPTION",
                            DisplayName = "ASSISTANT MANAGER",
                            Name = "ASSISTANT MANAGER",
                            Permissions = ""
                        },
                        new
                        {
                            Id = 9,
                            Description = "DESCRIPTION",
                            DisplayName = "JUNIOR MANAGER",
                            Name = "JUNIOR MANAGER",
                            Permissions = ""
                        },
                        new
                        {
                            Id = 10,
                            Description = "DESCRIPTION",
                            DisplayName = "SENIOR ENGINEER",
                            Name = "SENIOR ENGINEER",
                            Permissions = ""
                        },
                        new
                        {
                            Id = 11,
                            Description = "DESCRIPTION",
                            DisplayName = "ENGINEER",
                            Name = "ENGINEER",
                            Permissions = ""
                        },
                        new
                        {
                            Id = 12,
                            Description = "DESCRIPTION",
                            DisplayName = "JUNIOR ENGINEER",
                            Name = "JUNIOR ENGINEER",
                            Permissions = ""
                        },
                        new
                        {
                            Id = 13,
                            Description = "DESCRIPTION",
                            DisplayName = "SUPERVISOR",
                            Name = "SUPERVISOR",
                            Permissions = ""
                        },
                        new
                        {
                            Id = 14,
                            Description = "DESCRIPTION",
                            DisplayName = "ASSISTANT SUPERVISOR",
                            Name = "ASSISTANT SUPERVISOR",
                            Permissions = ""
                        },
                        new
                        {
                            Id = 15,
                            Description = "DESCRIPTION",
                            DisplayName = "TECHNICIAN",
                            Name = "TECHNICIAN",
                            Permissions = ""
                        },
                        new
                        {
                            Id = 16,
                            Description = "DESCRIPTION",
                            DisplayName = "HELPER",
                            Name = "HELPER",
                            Permissions = ""
                        },
                        new
                        {
                            Id = 17,
                            Description = "DESCRIPTION",
                            DisplayName = "UNDER TRAINING",
                            Name = "UNDER TRAINING",
                            Permissions = ""
                        },
                        new
                        {
                            Id = 18,
                            Description = "Default user access",
                            DisplayName = "User",
                            Name = "User",
                            Permissions = ""
                        });
                });

            modelBuilder.Entity("Digital.Api.Models.RoleAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Dept")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Desc")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<string>("PostTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Wing")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("RoleAssignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Dept = "P & P",
                            Desc = "DEVELOPER",
                            EmployeeCode = "DEE300426132",
                            EmployeeId = 1,
                            EmployeeName = "TEJESH GUDLA",
                            GroupId = 12,
                            GroupName = "JUNIOR ENGINEER",
                            LocationId = 1,
                            LocationName = "VISAKHAPATNAM",
                            PostId = 1,
                            PostTitle = "SOFTWARE DEVELOPER3",
                            Wing = "ELECTRICAL"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Dept = "P & P",
                            Desc = "Welder",
                            EmployeeCode = "DEE130426131",
                            EmployeeId = 2,
                            EmployeeName = "GANDIBOINA GOWRI PRASAD",
                            GroupId = 15,
                            GroupName = "TECHNICIAN",
                            LocationId = 1,
                            LocationName = "VISAKHAPATNAM",
                            PostId = 2,
                            PostTitle = "Welder",
                            Wing = "CIVIL"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Dept = "P & P",
                            Desc = "DEE HQ OFFICE ADMINISTRATIVE",
                            EmployeeCode = "DEE040426129",
                            EmployeeId = 3,
                            EmployeeName = "SAYAD SARFARAZ",
                            GroupId = 14,
                            GroupName = "ASSISTANT SUPERVISOR",
                            LocationId = 1,
                            LocationName = "VISAKHAPATNAM",
                            PostId = 3,
                            PostTitle = "DEE HQ OFFICE ADMINISTRATOR",
                            Wing = "ELECTRICAL"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Dept = "P & P",
                            Desc = "desc",
                            EmployeeCode = "DEE030426128",
                            EmployeeId = 4,
                            EmployeeName = "KANDREGULA KOTESWARA RAO",
                            GroupId = 15,
                            GroupName = "TECHNICIAN",
                            LocationId = 1,
                            LocationName = "VISAKHAPATNAM",
                            PostId = 4,
                            PostTitle = "ELECTRICAL INTEGRATION",
                            Wing = "ELECTRICAL"
                        });
                });

            modelBuilder.Entity("Digital.Api.Models.SalesInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("GstAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PayAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("SalesInvoices");
                });

            modelBuilder.Entity("Digital.Api.Models.SalesInvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GstPercentage")
                        .HasColumnType("numeric");

                    b.Property<string>("Hsn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric");

                    b.Property<int>("SalesInvoiceId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SalesInvoiceId");

                    b.ToTable("SalesInvoiceItems");
                });

            modelBuilder.Entity("Digital.Api.Models.SubGst", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DepartmentOfficer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GstNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfficerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("SubGsts");
                });

            modelBuilder.Entity("Digital.Api.Models.SubLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("SubLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "GRSE FOJ",
                            LocationId = 4,
                            Name = "GRSE FOJ"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "AFLS MUSTERING POINT",
                            LocationId = 1,
                            Name = "INS DEGA BLD"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "N/A",
                            LocationId = 3,
                            Name = "LION GATE"
                        });
                });

            modelBuilder.Entity("Digital.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Digital.Api.Models.Wing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<int>("UserCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Wings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 22, 5, 56, 0, 0, DateTimeKind.Utc),
                            Description = "DESC",
                            Name = "ELECTRICAL",
                            Status = true,
                            UserCount = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 22, 5, 56, 0, 0, DateTimeKind.Utc),
                            Description = "DEC",
                            Name = "CIVIL",
                            Status = true,
                            UserCount = 0
                        });
                });

            modelBuilder.Entity("Digital.Api.Models.Department", b =>
                {
                    b.HasOne("Digital.Api.Models.CompanyGst", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyGstNumber");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Digital.Api.Models.DesignationOfficer", b =>
                {
                    b.HasOne("Digital.Api.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Digital.Api.Models.Employee", b =>
                {
                    b.HasOne("Digital.Api.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Digital.Api.Models.DesignationOfficer", "DesignationOfficer")
                        .WithMany()
                        .HasForeignKey("DesignationOfficerId");

                    b.HasOne("Digital.Api.Models.Location", "Location")
                        .WithMany("Employees")
                        .HasForeignKey("LocationId");

                    b.Navigation("Department");

                    b.Navigation("DesignationOfficer");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Digital.Api.Models.EmployeeFamilyMember", b =>
                {
                    b.HasOne("Digital.Api.Models.Employee", "Employee")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Digital.Api.Models.EmployeeFund", b =>
                {
                    b.HasOne("Digital.Api.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Digital.Api.Models.EmployeeProfileUpdateRequest", b =>
                {
                    b.HasOne("Digital.Api.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Digital.Api.Models.LocationHead", b =>
                {
                    b.HasOne("Digital.Api.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Digital.Api.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Digital.Api.Models.PostGroupingItem", b =>
                {
                    b.HasOne("Digital.Api.Models.PostGrouping", "PostGrouping")
                        .WithMany("PostGroupingItems")
                        .HasForeignKey("PostGroupingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Digital.Api.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("PostGrouping");
                });

            modelBuilder.Entity("Digital.Api.Models.PurchaseInvoiceItem", b =>
                {
                    b.HasOne("Digital.Api.Models.PurchaseInvoice", null)
                        .WithMany("Items")
                        .HasForeignKey("PurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Digital.Api.Models.QuotationItem", b =>
                {
                    b.HasOne("Digital.Api.Models.Quotation", null)
                        .WithMany("Items")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Digital.Api.Models.SalesInvoiceItem", b =>
                {
                    b.HasOne("Digital.Api.Models.SalesInvoice", null)
                        .WithMany("Items")
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Digital.Api.Models.SubLocation", b =>
                {
                    b.HasOne("Digital.Api.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Digital.Api.Models.User", b =>
                {
                    b.HasOne("Digital.Api.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Digital.Api.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Digital.Api.Models.Employee", b =>
                {
                    b.Navigation("FamilyMembers");
                });

            modelBuilder.Entity("Digital.Api.Models.Location", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Digital.Api.Models.PostGrouping", b =>
                {
                    b.Navigation("PostGroupingItems");
                });

            modelBuilder.Entity("Digital.Api.Models.PurchaseInvoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Digital.Api.Models.Quotation", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Digital.Api.Models.SalesInvoice", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
