--
-- PostgreSQL database dump
--

\restrict hEGtchCe9tn4Op6yD9EjqfTPcU2jSoTsKQjNGepgfELyc7IfAEQUCmHh2kRijtQ

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: BankDetails; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BankDetails" (
    "EmpId" text NOT NULL,
    "CompanyName" text NOT NULL,
    "BankName" text NOT NULL,
    "AccountNo" text NOT NULL,
    "IfscCode" text NOT NULL,
    "SwiftCode" text NOT NULL,
    "MicrCode" text NOT NULL,
    "BranchName" text NOT NULL,
    "AccountHolder" text NOT NULL,
    "Category" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL
);


ALTER TABLE public."BankDetails" OWNER TO postgres;

--
-- Name: Banks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Banks" (
    "Id" integer NOT NULL,
    "BankName" character varying(255) NOT NULL,
    "Description" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL
);


ALTER TABLE public."Banks" OWNER TO postgres;

--
-- Name: Banks_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Banks" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Banks_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Categories" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "PhotoPath" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL
);


ALTER TABLE public."Categories" OWNER TO postgres;

--
-- Name: Categories_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Categories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Categories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: CompanyGsts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CompanyGsts" (
    "GstNumber" character varying(50) NOT NULL,
    "GstStateCode" text NOT NULL,
    "CompanyName" character varying(255) NOT NULL,
    "PanNumber" text NOT NULL,
    "TanNumber" text NOT NULL,
    "MobileNumber" text NOT NULL,
    "StateName" text NOT NULL,
    "Email" text NOT NULL,
    "PinCode" text NOT NULL,
    "CompanyAddress" text NOT NULL,
    "Remarks" text NOT NULL,
    "CompanyEstablished" timestamp without time zone,
    "City" text NOT NULL,
    "GstType" text NOT NULL,
    "DealsIn" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "Color" text DEFAULT ''::text NOT NULL,
    "FooterPath" text DEFAULT ''::text NOT NULL,
    "HeaderPath" text DEFAULT ''::text NOT NULL,
    "LogoPath" text DEFAULT ''::text NOT NULL,
    "SecondaryMobileNo" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."CompanyGsts" OWNER TO postgres;

--
-- Name: DeliveryDetails; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."DeliveryDetails" (
    "Id" integer NOT NULL,
    "CompanyName" character varying(255) NOT NULL,
    "State" text NOT NULL,
    "MobileNo" text NOT NULL,
    "Email" text NOT NULL,
    "PinCode" text NOT NULL,
    "Remarks" text NOT NULL,
    "Location" text NOT NULL,
    "Address" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL
);


ALTER TABLE public."DeliveryDetails" OWNER TO postgres;

--
-- Name: DeliveryDetails_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."DeliveryDetails" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DeliveryDetails_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Denominations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Denominations" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL
);


ALTER TABLE public."Denominations" OWNER TO postgres;

--
-- Name: Denominations_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Denominations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Denominations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Departments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Departments" (
    "Id" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "CompanyGstNumber" character varying(50),
    "CreatedAt" timestamp without time zone DEFAULT '-infinity'::timestamp without time zone NOT NULL,
    "Description" character varying(500) DEFAULT ''::character varying NOT NULL,
    "Status" boolean DEFAULT false NOT NULL
);


ALTER TABLE public."Departments" OWNER TO postgres;

--
-- Name: Departments_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Departments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Departments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: DesignationOfficers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."DesignationOfficers" (
    "Id" integer NOT NULL,
    "DesignationName" character varying(255) NOT NULL,
    "OfficerName" character varying(255) NOT NULL,
    "OfficerId" character varying(100) NOT NULL,
    "MobileNumber" character varying(20) NOT NULL,
    "Status" boolean NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "EndTime" timestamp without time zone,
    "StartTime" timestamp without time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    "DepartmentId" integer
);


ALTER TABLE public."DesignationOfficers" OWNER TO postgres;

--
-- Name: DesignationOfficers_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."DesignationOfficers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DesignationOfficers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Documents; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Documents" (
    "Id" integer NOT NULL,
    "EmployeeEmail" text NOT NULL,
    "Category" text NOT NULL,
    "SubCategory" text NOT NULL,
    "SubSubCategory" text NOT NULL,
    "DocumentName" text NOT NULL,
    "FilePath" text NOT NULL,
    "FileType" text NOT NULL,
    "FileSize" bigint NOT NULL,
    "Remarks" text NOT NULL,
    "UploadedAt" timestamp without time zone NOT NULL
);


ALTER TABLE public."Documents" OWNER TO postgres;

--
-- Name: Documents_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Documents" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Documents_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: EmployeeFamilyMembers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EmployeeFamilyMembers" (
    "Id" integer NOT NULL,
    "EmployeeId" integer NOT NULL,
    "Name" character varying(150) NOT NULL,
    "Relation" character varying(50),
    "DateOfBirth" text,
    "MealType" character varying(10),
    "CreatedAt" timestamp without time zone NOT NULL
);


ALTER TABLE public."EmployeeFamilyMembers" OWNER TO postgres;

--
-- Name: EmployeeFamilyMembers_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EmployeeFamilyMembers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EmployeeFamilyMembers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: EmployeeFunds; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EmployeeFunds" (
    "Id" integer NOT NULL,
    "EmployeeId" integer NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "GivenDate" timestamp without time zone NOT NULL,
    "Purpose" character varying(500) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "RefNo" character varying(100) NOT NULL,
    "RecordedBy" character varying(100) NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL
);


ALTER TABLE public."EmployeeFunds" OWNER TO postgres;

--
-- Name: EmployeeFunds_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EmployeeFunds" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EmployeeFunds_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: EmployeeRequiredRules; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EmployeeRequiredRules" (
    "Id" integer NOT NULL,
    "EmployeeCode" boolean NOT NULL,
    "Location" boolean NOT NULL,
    "AnnualSalary" boolean NOT NULL,
    "CoreQualification" boolean NOT NULL,
    "Remarks" boolean NOT NULL,
    "BloodGroup" boolean NOT NULL,
    "Religion" boolean NOT NULL,
    "Category" boolean NOT NULL,
    "AlternateNumber" boolean NOT NULL,
    "AadharNumber" boolean NOT NULL,
    "PanNumber" boolean NOT NULL,
    "UanNumber" boolean NOT NULL,
    "EsicNumber" boolean NOT NULL,
    "PassportNumber" boolean NOT NULL,
    "PvcNumber" boolean NOT NULL,
    "BankDetails" boolean NOT NULL,
    "NomineeDetails" boolean NOT NULL,
    "CurrentAddress" boolean DEFAULT false NOT NULL,
    "DateOfBirth" boolean DEFAULT false NOT NULL,
    "DateOfJoining" boolean DEFAULT false NOT NULL,
    "Department" boolean DEFAULT false NOT NULL,
    "Designation" boolean DEFAULT false NOT NULL,
    "EmergencyName" boolean DEFAULT false NOT NULL,
    "EmergencyPhone" boolean DEFAULT false NOT NULL,
    "EmergencyRelation" boolean DEFAULT false NOT NULL,
    "FullName" boolean DEFAULT false NOT NULL,
    "Gender" boolean DEFAULT false NOT NULL,
    "MaritalStatus" boolean DEFAULT false NOT NULL,
    "MobileNumber" boolean DEFAULT false NOT NULL,
    "OfficialEmail" boolean DEFAULT false NOT NULL,
    "PermanentAddress" boolean DEFAULT false NOT NULL,
    "Photo" boolean DEFAULT false NOT NULL
);


ALTER TABLE public."EmployeeRequiredRules" OWNER TO postgres;

--
-- Name: EmployeeRequiredRules_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EmployeeRequiredRules" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EmployeeRequiredRules_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Employees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Employees" (
    "EmployeeId" text,
    "Name" character varying(150) NOT NULL,
    "Email" text NOT NULL,
    "DepartmentId" integer,
    "LocationId" integer,
    "Role" text NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "Id" integer NOT NULL,
    "AnnualSalary" text,
    "Qualification" text,
    "Remarks" text,
    "TemporaryPassword" text,
    "DesignationOfficerId" integer,
    "AadharNumber" text,
    "AccountNumber" text,
    "AccountType" text,
    "AlternateNumber" text,
    "BankName" text,
    "BloodGroup" text,
    "BranchName" text,
    "Category" text,
    "CurrentAddress" text,
    "DateOfBirth" text,
    "DateOfJoining" text,
    "Designation" text,
    "EmergencyContactName" text,
    "EmergencyContactPhone" text,
    "EmergencyContactRelation" text,
    "EsicNumber" text,
    "Gender" text,
    "IfscCode" text,
    "MaritalStatus" text,
    "MobileNumber" text,
    "NomineeDOB" text,
    "NomineeName" text,
    "NomineeRelation" text,
    "PanNumber" text,
    "PassportNumber" text,
    "PassportValidUpto" text,
    "PermanentAddress" text,
    "PvcNumber" text,
    "PvcValidUpto" text,
    "Religion" text,
    "UanNumber" text,
    "ApprovedAt" timestamp without time zone,
    "ApprovedBy" text
);


ALTER TABLE public."Employees" OWNER TO postgres;

--
-- Name: Employees_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Employees" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Employees_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: HsnCodes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."HsnCodes" (
    "Id" integer NOT NULL,
    "Code" text NOT NULL,
    "Description" text NOT NULL
);


ALTER TABLE public."HsnCodes" OWNER TO postgres;

--
-- Name: HsnCodes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."HsnCodes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."HsnCodes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: LocationHeads; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."LocationHeads" (
    "Id" integer NOT NULL,
    "LocationId" integer NOT NULL,
    "EmployeeId" integer NOT NULL,
    "AssignedAt" timestamp without time zone NOT NULL
);


ALTER TABLE public."LocationHeads" OWNER TO postgres;

--
-- Name: LocationHeads_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."LocationHeads" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."LocationHeads_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Locations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Locations" (
    "Id" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "CreatedAt" timestamp without time zone DEFAULT '-infinity'::timestamp without time zone NOT NULL,
    "Description" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."Locations" OWNER TO postgres;

--
-- Name: Locations_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Locations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Locations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: MasterData; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MasterData" (
    "Id" integer NOT NULL,
    "Category" character varying(100) NOT NULL,
    "Value" character varying(255) NOT NULL,
    "Description" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "PhotoPath" text DEFAULT ''::text NOT NULL,
    "ParentId" integer,
    "ShortName" text DEFAULT ''::text NOT NULL,
    "Location" text DEFAULT ''::text NOT NULL,
    "GstStateCode" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."MasterData" OWNER TO postgres;

--
-- Name: MasterData_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."MasterData" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MasterData_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PostGroupingItems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PostGroupingItems" (
    "Id" integer NOT NULL,
    "PostGroupingId" integer NOT NULL,
    "PostId" integer NOT NULL
);


ALTER TABLE public."PostGroupingItems" OWNER TO postgres;

--
-- Name: PostGroupingItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PostGroupingItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PostGroupingItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PostGroupings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PostGroupings" (
    "Id" integer NOT NULL,
    "Name" character varying(150) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL
);


ALTER TABLE public."PostGroupings" OWNER TO postgres;

--
-- Name: PostGroupings_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PostGroupings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PostGroupings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Posts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Posts" (
    "Id" integer NOT NULL,
    "GroupId" integer NOT NULL,
    "GroupName" character varying(100) NOT NULL,
    "Wing" character varying(100) NOT NULL,
    "Dept" character varying(100) NOT NULL,
    "Title" character varying(255) NOT NULL,
    "Desc" character varying(500) NOT NULL,
    "Date" timestamp without time zone NOT NULL
);


ALTER TABLE public."Posts" OWNER TO postgres;

--
-- Name: Posts_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Posts" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Posts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ProfileUpdateRequests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ProfileUpdateRequests" (
    "Id" integer NOT NULL,
    "EmployeeId" integer NOT NULL,
    "FieldName" character varying(100) NOT NULL,
    "OldValue" character varying(500),
    "NewValue" character varying(500) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "RejectionReason" character varying(500),
    "RequestedAt" timestamp without time zone NOT NULL,
    "ReviewedAt" timestamp without time zone,
    "ReviewedBy" character varying(100)
);


ALTER TABLE public."ProfileUpdateRequests" OWNER TO postgres;

--
-- Name: ProfileUpdateRequests_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ProfileUpdateRequests" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProfileUpdateRequests_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Projects; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Projects" (
    "ProjectId" text NOT NULL,
    "Name" character varying(255) NOT NULL,
    "Wing" text NOT NULL,
    "Department" text NOT NULL,
    "Location" text NOT NULL,
    "Post" text NOT NULL,
    "CreatedBy" text NOT NULL,
    "Client" text NOT NULL,
    "Gst" text NOT NULL,
    "Value" text NOT NULL,
    "StartDate" timestamp without time zone,
    "EndDate" timestamp without time zone,
    "Status" text NOT NULL,
    "Priority" text NOT NULL,
    "Description" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "FilePath" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."Projects" OWNER TO postgres;

--
-- Name: PurchaseInvoiceItems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PurchaseInvoiceItems" (
    "Id" integer NOT NULL,
    "PurchaseInvoiceId" integer NOT NULL,
    "Category" text NOT NULL,
    "Subcategory" text NOT NULL,
    "Brand" text NOT NULL,
    "Description" text NOT NULL,
    "Capacity" text NOT NULL,
    "Hsn" text NOT NULL,
    "Denom" text NOT NULL,
    "Quantity" integer NOT NULL,
    "Mrp" numeric NOT NULL,
    "CostRate" numeric NOT NULL,
    "SellPrice" numeric NOT NULL,
    "SerialNo" text NOT NULL,
    "ExpiryDate" timestamp without time zone,
    "Location" text NOT NULL,
    "PurchaseType" text NOT NULL,
    "Igst" numeric NOT NULL,
    "Cgst" numeric NOT NULL,
    "Sgst" numeric NOT NULL,
    "Amount" numeric NOT NULL,
    "Total" numeric NOT NULL
);


ALTER TABLE public."PurchaseInvoiceItems" OWNER TO postgres;

--
-- Name: PurchaseInvoiceItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PurchaseInvoiceItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PurchaseInvoiceItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PurchaseInvoices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PurchaseInvoices" (
    "Id" integer NOT NULL,
    "Designation" text NOT NULL,
    "ExpenseType" text NOT NULL,
    "CompanyName" text NOT NULL,
    "InvoiceNo" text NOT NULL,
    "InvoiceDate" timestamp without time zone,
    "PanCard" text NOT NULL,
    "TotalIgst" numeric NOT NULL,
    "TotalCgst" numeric NOT NULL,
    "TotalSgst" numeric NOT NULL,
    "AmountExclGst" numeric NOT NULL,
    "RoundOff" numeric NOT NULL,
    "TotalAmount" numeric NOT NULL,
    "InvoiceFilePath" text,
    "CreatedAt" timestamp without time zone NOT NULL,
    "PaidAmount" numeric DEFAULT 0.0 NOT NULL
);


ALTER TABLE public."PurchaseInvoices" OWNER TO postgres;

--
-- Name: PurchaseInvoices_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PurchaseInvoices" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PurchaseInvoices_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: QuotationItems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."QuotationItems" (
    "Id" integer NOT NULL,
    "QuotationId" integer NOT NULL,
    "Category" text NOT NULL,
    "Subcategory" text NOT NULL,
    "Brand" text NOT NULL,
    "Description" text NOT NULL,
    "Capacity" text NOT NULL,
    "Hsn" text NOT NULL,
    "Denom" text NOT NULL,
    "Quantity" integer NOT NULL,
    "Price" numeric NOT NULL,
    "Igst" numeric NOT NULL,
    "Cgst" numeric NOT NULL,
    "Sgst" numeric NOT NULL,
    "Amount" numeric NOT NULL,
    "Total" numeric NOT NULL
);


ALTER TABLE public."QuotationItems" OWNER TO postgres;

--
-- Name: QuotationItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."QuotationItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."QuotationItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Quotations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Quotations" (
    "Id" integer NOT NULL,
    "QuotationNumber" text NOT NULL,
    "ExpenseType" text NOT NULL,
    "CompanyName" text NOT NULL,
    "ProjectName" text NOT NULL,
    "InvoiceDate" timestamp without time zone,
    "ValidityDays" text NOT NULL,
    "DeliveryDays" text NOT NULL,
    "WarrantyDays" text NOT NULL,
    "InquiryNo" text NOT NULL,
    "InquiryDate" timestamp without time zone,
    "Remarks" text NOT NULL,
    "GstType" text NOT NULL,
    "TotalIgst" numeric NOT NULL,
    "TotalCgst" numeric NOT NULL,
    "TotalSgst" numeric NOT NULL,
    "AmountExclGst" numeric NOT NULL,
    "RoundOff" numeric NOT NULL,
    "TotalAmount" numeric NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "CreatedBy" text DEFAULT ''::text NOT NULL,
    "Department" text DEFAULT ''::text NOT NULL,
    "Post" text DEFAULT ''::text NOT NULL,
    "Wing" text DEFAULT ''::text NOT NULL,
    "Status" text DEFAULT ''::text NOT NULL,
    "Subject" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."Quotations" OWNER TO postgres;

--
-- Name: Quotations_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Quotations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Quotations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: RoleAssignments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."RoleAssignments" (
    "Id" integer NOT NULL,
    "GroupId" integer NOT NULL,
    "GroupName" character varying(100) NOT NULL,
    "PostId" integer NOT NULL,
    "PostTitle" character varying(255) NOT NULL,
    "Wing" character varying(100) NOT NULL,
    "Dept" character varying(100) NOT NULL,
    "LocationId" integer NOT NULL,
    "LocationName" character varying(100) NOT NULL,
    "EmployeeId" integer NOT NULL,
    "EmployeeName" character varying(100) NOT NULL,
    "EmployeeCode" character varying(50),
    "Desc" character varying(500),
    "Date" timestamp without time zone NOT NULL
);


ALTER TABLE public."RoleAssignments" OWNER TO postgres;

--
-- Name: RoleAssignments_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."RoleAssignments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RoleAssignments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Roles" (
    "Id" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "DisplayName" character varying(100) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "Permissions" text NOT NULL
);


ALTER TABLE public."Roles" OWNER TO postgres;

--
-- Name: Roles_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Roles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Roles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SalesInvoiceItems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SalesInvoiceItems" (
    "Id" integer NOT NULL,
    "SalesInvoiceId" integer NOT NULL,
    "Description" text NOT NULL,
    "Hsn" text NOT NULL,
    "Quantity" integer NOT NULL,
    "Rate" numeric NOT NULL,
    "GstPercentage" numeric NOT NULL,
    "Amount" numeric NOT NULL,
    "Total" numeric NOT NULL
);


ALTER TABLE public."SalesInvoiceItems" OWNER TO postgres;

--
-- Name: SalesInvoiceItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SalesInvoiceItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SalesInvoiceItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SalesInvoices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SalesInvoices" (
    "Id" integer NOT NULL,
    "ClientName" text NOT NULL,
    "InvoiceNo" text NOT NULL,
    "InvoiceDate" timestamp without time zone,
    "Amount" numeric NOT NULL,
    "GstAmount" numeric NOT NULL,
    "TotalAmount" numeric NOT NULL,
    "PayAmount" numeric NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL
);


ALTER TABLE public."SalesInvoices" OWNER TO postgres;

--
-- Name: SalesInvoices_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SalesInvoices" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SalesInvoices_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SubGsts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SubGsts" (
    "Id" integer NOT NULL,
    "CompanyName" character varying(255) NOT NULL,
    "OfficerName" text CONSTRAINT "SubGsts_State_not_null" NOT NULL,
    "Mobile" text NOT NULL,
    "GstNumber" text CONSTRAINT "SubGsts_PinCode_not_null" NOT NULL,
    "Remarks" text NOT NULL,
    "Department" text CONSTRAINT "SubGsts_Location_not_null" NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "Status" boolean DEFAULT false NOT NULL,
    "DepartmentOfficer" text DEFAULT ''::text NOT NULL,
    "Designation" text DEFAULT ''::text NOT NULL,
    "EndDate" timestamp without time zone,
    "StartDate" timestamp without time zone
);


ALTER TABLE public."SubGsts" OWNER TO postgres;

--
-- Name: SubGsts_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SubGsts" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SubGsts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SubLocations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SubLocations" (
    "Id" integer NOT NULL,
    "LocationId" integer NOT NULL,
    "Name" character varying(150) NOT NULL,
    "Description" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL
);


ALTER TABLE public."SubLocations" OWNER TO postgres;

--
-- Name: SubLocations_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SubLocations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SubLocations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "FullName" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "RoleId" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Wings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Wings" (
    "Id" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "Status" boolean NOT NULL,
    "UserCount" integer NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL
);


ALTER TABLE public."Wings" OWNER TO postgres;

--
-- Name: Wings_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Wings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Wings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: BankDetails; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."BankDetails" ("EmpId", "CompanyName", "BankName", "AccountNo", "IfscCode", "SwiftCode", "MicrCode", "BranchName", "AccountHolder", "Category", "CreatedAt") FROM stdin;
\.


--
-- Data for Name: Banks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Banks" ("Id", "BankName", "Description", "CreatedAt") FROM stdin;
1	STATE BANK OF INDIA	SBI	2026-05-27 05:57:28.624817
2	HDFC BANK	HDFC	2026-05-27 05:57:28.624872
3	ICICI BANK	ICICI	2026-05-27 05:57:28.624872
4	CANARA BANK	CANARA	2026-05-27 05:57:28.624873
\.


--
-- Data for Name: Categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Categories" ("Id", "Name", "Description", "PhotoPath", "CreatedAt") FROM stdin;
\.


--
-- Data for Name: CompanyGsts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."CompanyGsts" ("GstNumber", "GstStateCode", "CompanyName", "PanNumber", "TanNumber", "MobileNumber", "StateName", "Email", "PinCode", "CompanyAddress", "Remarks", "CompanyEstablished", "City", "GstType", "DealsIn", "CreatedAt", "Color", "FooterPath", "HeaderPath", "LogoPath", "SecondaryMobileNo") FROM stdin;
27AADCD1234A1Z1	27	DIGITAL NEW ENTERPRISES	AADCD1234A	TAN12345	9876543210	Maharashtra	contact@digital.com	400001	Mumbai Address	Remarks	\N	Mumbai	Regular	Services	2026-05-27 05:57:28.624664					
27BBBDD4321B1Z2	27	TECH SOLUTIONS LTD	BBBDD4321B	TAN54321	9988776655	Karnataka	info@techsolutions.com	560001	Bangalore Address	Remarks	\N	Bangalore	Regular	IT Services	2026-05-27 05:57:28.624756					
27CCCCD9999C1Z3	27	GLOBAL LOGISTICS CORP	CCCCD9999C	TAN99999	9123456789	Gujarat	support@global.com	380001	Ahmedabad Address	Remarks	\N	Ahmedabad	Regular	Logistics	2026-05-27 05:57:28.624756					
\.


--
-- Data for Name: DeliveryDetails; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."DeliveryDetails" ("Id", "CompanyName", "State", "MobileNo", "Email", "PinCode", "Remarks", "Location", "Address", "CreatedAt") FROM stdin;
1	DIGITAL NEW ENTERPRISES	ANDHRA PRADESH	9160907215	tejesharyagud@gmail.com	530011	jikdfvbdej	Vizag	61-5-15 venkannapalem malkapuram\nvisakhapatnam	2026-05-21 05:01:31.897318
\.


--
-- Data for Name: Denominations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Denominations" ("Id", "Name") FROM stdin;
\.


--
-- Data for Name: Departments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Departments" ("Id", "Name", "CompanyGstNumber", "CreatedAt", "Description", "Status") FROM stdin;
2	IT	27AADCD1234A1Z1	2025-12-22 05:57:00	DSEC	t
3	SALES	27AADCD1234A1Z1	2025-12-22 05:58:00	DESCRIPTION	t
4	R & D	27AADCD1234A1Z1	2025-12-22 05:58:00	RESEARCH AND DEVELOPMENT	t
5	P & P	27AADCD1234A1Z1	2025-12-22 05:59:00	PLANNING AND PRODUCTION	t
6	ARYA	27AADCD1234A1Z1	2026-05-21 09:44:15.373	hjkbhjk	t
1	HR	27AADCD1234A1Z1	2025-12-22 05:57:00	DSEC	t
7	IT - IT Support Specialist - Tejesh G	\N	2026-05-22 09:36:56.38668		t
\.


--
-- Data for Name: DesignationOfficers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."DesignationOfficers" ("Id", "DesignationName", "OfficerName", "OfficerId", "MobileNumber", "Status", "CreatedAt", "EndTime", "StartTime", "DepartmentId") FROM stdin;
1	Software Engineer	N/A	N/A	9999999999	t	2026-05-20 12:05:02.381503	\N	2026-05-20 12:05:02.381502	3
2	Lead Developer	N/A	N/A	9999999999	t	2026-05-20 12:05:02.449202	\N	2026-05-20 12:05:02.449202	3
3	IT Support Specialist	N/A	N/A	9999999999	t	2026-05-20 12:05:02.455837	\N	2026-05-20 12:05:02.455836	3
4	Project Manager	N/A	N/A	9999999999	t	2026-05-20 12:05:02.461518	\N	2026-05-20 12:05:02.461518	2
5	Site Engineer	N/A	N/A	9999999999	t	2026-05-20 12:05:02.46694	\N	2026-05-20 12:05:02.46694	2
6	Civil Surveyor	N/A	N/A	9999999999	t	2026-05-20 12:05:02.473805	\N	2026-05-20 12:05:02.473805	2
7	Planning Officer	N/A	N/A	9999999999	t	2026-05-20 12:05:02.477569	\N	2026-05-20 12:05:02.477569	1
8	Procurement Manager	N/A	N/A	9999999999	t	2026-05-20 12:05:02.481703	\N	2026-05-20 12:05:02.481703	1
\.


--
-- Data for Name: Documents; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Documents" ("Id", "EmployeeEmail", "Category", "SubCategory", "SubSubCategory", "DocumentName", "FilePath", "FileType", "FileSize", "Remarks", "UploadedAt") FROM stdin;
\.


--
-- Data for Name: EmployeeFamilyMembers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."EmployeeFamilyMembers" ("Id", "EmployeeId", "Name", "Relation", "DateOfBirth", "MealType", "CreatedAt") FROM stdin;
1	107	gvygyv g	Brother	2026-05-28	Veg	2026-05-26 05:43:53.381406
\.


--
-- Data for Name: EmployeeFunds; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."EmployeeFunds" ("Id", "EmployeeId", "Amount", "GivenDate", "Purpose", "Status", "RefNo", "RecordedBy", "CreatedAt") FROM stdin;
1	1	15000.00	2026-04-15 00:00:00	Office Supplies & Development Kit Reimbursement	Approved	FT-948274	AMANTU	2026-04-15 10:00:00
2	3	8500.00	2026-05-10 00:00:00	Client Site Travel & Accommodation Allowance	Released	FT-201847	AMANTU	2026-05-10 11:30:00
3	102	12000.00	2026-05-18 00:00:00	Technical Certification Fee Reimbursement	Pending	FT-583921	AMANTU	2026-05-18 14:15:00
\.


--
-- Data for Name: EmployeeRequiredRules; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."EmployeeRequiredRules" ("Id", "EmployeeCode", "Location", "AnnualSalary", "CoreQualification", "Remarks", "BloodGroup", "Religion", "Category", "AlternateNumber", "AadharNumber", "PanNumber", "UanNumber", "EsicNumber", "PassportNumber", "PvcNumber", "BankDetails", "NomineeDetails", "CurrentAddress", "DateOfBirth", "DateOfJoining", "Department", "Designation", "EmergencyName", "EmergencyPhone", "EmergencyRelation", "FullName", "Gender", "MaritalStatus", "MobileNumber", "OfficialEmail", "PermanentAddress", "Photo") FROM stdin;
1	f	f	f	t	f	t	f	t	f	t	t	f	f	f	f	t	f	t	t	t	t	t	t	t	t	f	t	t	t	t	t	t
\.


--
-- Data for Name: Employees; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Employees" ("EmployeeId", "Name", "Email", "DepartmentId", "LocationId", "Role", "Status", "CreatedAt", "UpdatedAt", "Id", "AnnualSalary", "Qualification", "Remarks", "TemporaryPassword", "DesignationOfficerId", "AadharNumber", "AccountNumber", "AccountType", "AlternateNumber", "BankName", "BloodGroup", "BranchName", "Category", "CurrentAddress", "DateOfBirth", "DateOfJoining", "Designation", "EmergencyContactName", "EmergencyContactPhone", "EmergencyContactRelation", "EsicNumber", "Gender", "IfscCode", "MaritalStatus", "MobileNumber", "NomineeDOB", "NomineeName", "NomineeRelation", "PanNumber", "PassportNumber", "PassportValidUpto", "PermanentAddress", "PvcNumber", "PvcValidUpto", "Religion", "UanNumber", "ApprovedAt", "ApprovedBy") FROM stdin;
DEE300426132	TEJESH GUDLA	tejeshgudla2@gmail.com	1	1	IT	Active	2026-04-30 00:00:00	\N	1	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N
DEE130426131	GANDIBOINA GOWRI PRASAD	gowriprasad111@gmail.com	1	1	ASSISTANT MANAGER	Active	2026-04-13 00:00:00	\N	2	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N
DEE040426130	RAVENDRA SINGH	ravendrasinghchouhan@gmail.com	2	2	SENIOR MANAGER	Active	2026-04-04 00:00:00	\N	3	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N
DEE210526104	Amantu	m@gmail.com	\N	\N	Employee	Active	2026-05-21 04:18:03.882821	2026-05-21 04:18:22.880854	4	3000000	B.E / B.TECH	IT	1234567890	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N
DEE210526108	Tejesh G	t@gmail.com	\N	\N	Employee	Active	2026-05-21 12:47:38.632172	2026-05-21 12:48:02.756395	104	30000	B.E / B.TECH	New one	1234567890	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N
DEE210526109	Arya	a@gmail.com	\N	\N	Employee	Active	2026-05-21 12:57:07.663751	2026-05-21 12:57:40.604628	105	10000	B.E / B.TECH	uyu	1234567890	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N
DEE260526110	Tejesh Arya Gudla	tejesharyagudla@gmail.com	7	7	Employee	Active	2026-05-26 05:43:53.171695	2026-05-26 05:51:02.534677	107	36996	B.E / B.TECH		1234567890	\N	845465569699	5985985858	Savings	9177010175		O+	hbbuhuiiu	General	61-5-15 VENKANNAPALEM MALKAPURAM\nVISAKHAPATNAM, VISAKHAPATANAM, Andhra Pradesh - 530011	2026-05-26	2026-05-27	IT	Tejesh Gudla	1984984994	Father	884548474	Male	51616hghb9	Single	9160907215	2026-05-27	hgchgcgfc ghvh	Father	65745545AC	jhkbj57678kj	2026-05-28	61-5-15 VENKANNAPALEM MALKAPURAM\nVISAKHAPATNAM, VISAKHAPATANAM, Andhra Pradesh - 530011	78787777	2026-05-27	Hindu	845555555585	\N	\N
DEE260526111			\N	\N	Employee	Active	2026-05-23 10:02:00.218426	2026-05-26 05:51:20.448174	106					\N									, ,  - 																		, ,  - 					\N	\N
DEE010126115	RANJAN YADAV	ranjan.yadav@digital.com	\N	1	Location Head	Active	2026-03-31 13:02:00	\N	101	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N
DEE251225102	ANUPAM KUMAR	anupam.kumar@digital.com	\N	3	Location Head	Active	2025-12-30 06:40:15	\N	102	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N
DEE251225103	SANJAY KUMAR MAHATO	sanjay.mahato@digital.com	\N	5	Location Head	Active	2026-03-31 14:26:42	\N	103	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N
\.


--
-- Data for Name: HsnCodes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."HsnCodes" ("Id", "Code", "Description") FROM stdin;
\.


--
-- Data for Name: LocationHeads; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."LocationHeads" ("Id", "LocationId", "EmployeeId", "AssignedAt") FROM stdin;
1	1	101	2026-03-31 13:02:00
2	3	102	2026-04-01 04:39:00
3	2	102	2026-04-01 04:39:00
4	5	103	2026-04-03 04:00:00
5	4	101	2026-04-03 04:15:00
\.


--
-- Data for Name: Locations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Locations" ("Id", "Name", "CreatedAt", "Description") FROM stdin;
1	VISAKHAPATNAM	2025-12-19 11:00:18	Main Office Location
2	KARWAR	2025-12-24 02:42:58	DESC
3	MUMBAI	2025-12-30 06:40:15	MUMBAI
4	KOLKATA	2026-01-02 06:01:30	WEST BENGAL
5	JAMNAGAR	2026-03-31 14:26:42	JAMNAGAR
6	KOCHIN	2026-03-31 14:28:28	KOCHIN
7	DUVVADA	2026-05-21 12:15:16.017434	new
\.


--
-- Data for Name: MasterData; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."MasterData" ("Id", "Category", "Value", "Description", "CreatedAt", "PhotoPath", "ParentId", "ShortName", "Location", "GstStateCode") FROM stdin;
1	Payment Mode	GPAY	GPAY	2026-05-20 10:47:41.915132		\N			
2	Payment Mode	ONLINE TRANSFER	ONLINE TRANSFER	2026-05-20 10:47:41.915301		\N			
3	Payment Mode	CHEQUE PAYMENT	CHEQUE PAYMENT	2026-05-20 10:47:41.915302		\N			
4	Payment Mode	CASH PAYMENT	CASH PAYMENT	2026-05-20 10:47:41.915302		\N			
5	Payment Mode	PHONEPE	PHONEPE	2026-05-20 10:47:41.915302		\N			
6	State	ANDHRA PRADESH		2026-05-20 10:47:41.915303		\N			
7	State	MAHARASHTRA		2026-05-20 10:47:41.915303		\N			
8	State	TAMIL NADU		2026-05-20 10:47:41.915304		\N			
9	Expense	FUEL		2026-05-20 10:47:41.915304		\N			
10	Expense	MAINTENANCE		2026-05-20 10:47:41.915304		\N			
11	Expense	SALARY		2026-05-20 10:47:41.915304		\N			
12	Category	HARDWARE	Computer Hardware	2026-05-20 10:47:41.915305		\N			
13	Category	SOFTWARE	Software Licenses	2026-05-20 10:47:41.915305		\N			
14	Category	FURNITURE	Office Furniture	2026-05-20 10:47:41.915305		\N			
15	Brand	DELL	Dell Computers	2026-05-20 10:47:41.915319		\N			
16	Brand	HP	HP Laptops	2026-05-20 10:47:41.91532		\N			
17	Brand	LOGITECH	Logitech Accessories	2026-05-20 10:47:41.91532		\N			
18	Sub Category	LAPTOPS	Portable Computers	2026-05-20 10:47:41.91532		\N			
19	Sub Category	MONITORS	Computer Displays	2026-05-20 10:47:41.91532		\N			
20	Post	DEVELOPER	Software Developer	2026-05-20 10:47:41.91532		\N			
21	Post	MANAGER	Project Manager	2026-05-20 10:47:41.915321		\N			
22	Post	ACCOUNTANT	Finance Team	2026-05-20 10:47:41.915321		\N			
23	Location	OFFICE A	Main Office	2026-05-20 10:47:41.915321		\N			
24	Location	WAREHOUSE	Primary Storage	2026-05-20 10:47:41.915321		\N			
25	Document Category	FINANCIAL DOCUMENTS	Company Financials, Tax and Accounts	2026-05-20 10:47:58.96985		\N			
26	Document Category	TECHNICAL DOCUMENTS	System Architecture and Source Code Diagrams	2026-05-20 10:47:58.96985		\N			
27	Document Category	LEGAL DOCUMENTS	NDA, SLA, Contracts and Compliance	2026-05-20 10:47:58.96985		\N			
28	Document Category	HUMAN RESOURCES	Offer Letters and Employee Profiles	2026-05-20 10:47:58.969851		\N			
29	Sub Document Category	TAX FILINGS	GST and Income Tax filings	2026-05-20 10:47:58.975283		25			
30	Sub Document Category	INVOICES & BILLS	Client and Vendor Invoices	2026-05-20 10:47:58.97561		25			
31	Sub Document Category	SYSTEM DIAGRAMS	Database and Network Blueprints	2026-05-20 10:47:58.97561		26			
32	Sub Document Category	CLIENT CONTRACTS	Signed service level agreements	2026-05-20 10:47:58.975611		27			
33	Sub-Sub Document Category	GST RETURNS	GSTR-1 and GSTR-3B filings	2026-05-20 10:47:58.984273		29			
34	Sub-Sub Document Category	INCOME TAX RETURNS	ITR filings	2026-05-20 10:47:58.984274		29			
35	Sub-Sub Document Category	SALES INVOICES	Invoices sent to customers	2026-05-20 10:47:58.984274		30			
36	Sub-Sub Document Category	PURCHASE INVOICES	Invoices received from suppliers	2026-05-20 10:47:58.984275		30			
37	Sub-Sub Document Category	DATABASE SCHEMAS	PostgreSQL and MySQL entity diagrams	2026-05-20 10:47:58.984275		31			
38	Sub Sub Document Category	GST RETURNS	GSTR-1 and GSTR-3B filings	2026-05-20 10:47:58.984275		29			
39	Sub Sub Document Category	INCOME TAX RETURNS	ITR filings	2026-05-20 10:47:58.984275		29			
40	Sub Sub Document Category	SALES INVOICES	Invoices sent to customers	2026-05-20 10:47:58.984275		30			
41	Sub Sub Document Category	PURCHASE INVOICES	Invoices received from suppliers	2026-05-20 10:47:58.984275		30			
42	Sub Sub Document Category	DATABASE SCHEMAS	PostgreSQL and MySQL entity diagrams	2026-05-20 10:47:58.984276		31			
\.


--
-- Data for Name: PostGroupingItems; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."PostGroupingItems" ("Id", "PostGroupingId", "PostId") FROM stdin;
\.


--
-- Data for Name: PostGroupings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."PostGroupings" ("Id", "Name", "Description", "CreatedAt") FROM stdin;
\.


--
-- Data for Name: Posts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Posts" ("Id", "GroupId", "GroupName", "Wing", "Dept", "Title", "Desc", "Date") FROM stdin;
1	12	JUNIOR ENGINEER	ELECTRICAL	P & P	SOFTWARE DEVELOPER3	DEVELOPER	2026-04-30 00:00:00
2	15	TECHNICIAN	CIVIL	P & P	Welder	Welder	2026-04-13 00:00:00
3	14	ASSISTANT SUPERVISOR	ELECTRICAL	P & P	DEE HQ OFFICE ADMINISTRATOR	DEE HQ OFFICE ADMINISTRATOR	2026-04-04 00:00:00
4	15	TECHNICIAN	ELECTRICAL	P & P	ELECTRICAL TECHNICIAN	ELECTRICAL TECHNICIAN	2026-04-03 00:00:00
\.


--
-- Data for Name: ProfileUpdateRequests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ProfileUpdateRequests" ("Id", "EmployeeId", "FieldName", "OldValue", "NewValue", "Status", "RejectionReason", "RequestedAt", "ReviewedAt", "ReviewedBy") FROM stdin;
1	1	Role	JUNIOR ENGINEER	SENIOR ENGINEER	Pending	\N	2026-05-19 09:00:00	\N	\N
2	3	Qualification	\N	B.Tech Civil Engineering	Pending	\N	2026-05-20 11:30:00	\N	\N
3	102	Email	anupam.kumar@digital.com	a.kumar@digital.com	Pending	\N	2026-05-21 08:00:00	\N	\N
\.


--
-- Data for Name: Projects; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Projects" ("ProjectId", "Name", "Wing", "Department", "Location", "Post", "CreatedBy", "Client", "Gst", "Value", "StartDate", "EndDate", "Status", "Priority", "Description", "CreatedAt", "FilePath") FROM stdin;
\.


--
-- Data for Name: PurchaseInvoiceItems; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."PurchaseInvoiceItems" ("Id", "PurchaseInvoiceId", "Category", "Subcategory", "Brand", "Description", "Capacity", "Hsn", "Denom", "Quantity", "Mrp", "CostRate", "SellPrice", "SerialNo", "ExpiryDate", "Location", "PurchaseType", "Igst", "Cgst", "Sgst", "Amount", "Total") FROM stdin;
\.


--
-- Data for Name: PurchaseInvoices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."PurchaseInvoices" ("Id", "Designation", "ExpenseType", "CompanyName", "InvoiceNo", "InvoiceDate", "PanCard", "TotalIgst", "TotalCgst", "TotalSgst", "AmountExclGst", "RoundOff", "TotalAmount", "InvoiceFilePath", "CreatedAt", "PaidAmount") FROM stdin;
\.


--
-- Data for Name: QuotationItems; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."QuotationItems" ("Id", "QuotationId", "Category", "Subcategory", "Brand", "Description", "Capacity", "Hsn", "Denom", "Quantity", "Price", "Igst", "Cgst", "Sgst", "Amount", "Total") FROM stdin;
\.


--
-- Data for Name: Quotations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Quotations" ("Id", "QuotationNumber", "ExpenseType", "CompanyName", "ProjectName", "InvoiceDate", "ValidityDays", "DeliveryDays", "WarrantyDays", "InquiryNo", "InquiryDate", "Remarks", "GstType", "TotalIgst", "TotalCgst", "TotalSgst", "AmountExclGst", "RoundOff", "TotalAmount", "CreatedAt", "CreatedBy", "Department", "Post", "Wing", "Status", "Subject") FROM stdin;
\.


--
-- Data for Name: RoleAssignments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."RoleAssignments" ("Id", "GroupId", "GroupName", "PostId", "PostTitle", "Wing", "Dept", "LocationId", "LocationName", "EmployeeId", "EmployeeName", "EmployeeCode", "Desc", "Date") FROM stdin;
1	12	JUNIOR ENGINEER	1	SOFTWARE DEVELOPER3	ELECTRICAL	P & P	1	VISAKHAPATNAM	1	TEJESH GUDLA	DEE300426132	DEVELOPER	2026-04-30 00:00:00
2	15	TECHNICIAN	2	Welder	CIVIL	P & P	1	VISAKHAPATNAM	2	GANDIBOINA GOWRI PRASAD	DEE130426131	Welder	2026-04-13 00:00:00
3	14	ASSISTANT SUPERVISOR	3	DEE HQ OFFICE ADMINISTRATOR	ELECTRICAL	P & P	1	VISAKHAPATNAM	3	SAYAD SARFARAZ	DEE040426129	DEE HQ OFFICE ADMINISTRATIVE	2026-04-04 00:00:00
5	5	IT	3	DEE HQ OFFICE ADMINISTRATOR	ELECTRICAL	P & P	1	VISAKHAPATNAM	1	TEJESH GUDLA	DEE300426132	klmklmk	2026-05-21 10:15:27.586435
4	15	TECHNICIAN	4	ELECTRICAL INTEGRATION	ELECTRICAL	P & P	1	VISAKHAPATNAM	4	KANDREGULA KOTESWARA RAO	DEE030426128	desc	2026-04-03 00:00:00
\.


--
-- Data for Name: Roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Roles" ("Id", "Name", "DisplayName", "Description", "Permissions") FROM stdin;
1	admin	Administrator	Full system access	
2	DIRECTOR	DIRECTOR	ADMIN	
3	MANAGING DIRECTOR	MANAGING DIRECTOR	DESC	
4	HR	HR	HR	
5	IT	IT	IT DEPARTMENT	
6	SENIOR MANAGER	SENIOR MANAGER	DESCRIPTION	
7	MANAGER	MANAGER	DESCRIPTION	
8	ASSISTANT MANAGER	ASSISTANT MANAGER	DESCRIPTION	
9	JUNIOR MANAGER	JUNIOR MANAGER	DESCRIPTION	
10	SENIOR ENGINEER	SENIOR ENGINEER	DESCRIPTION	
11	ENGINEER	ENGINEER	DESCRIPTION	
12	JUNIOR ENGINEER	JUNIOR ENGINEER	DESCRIPTION	
13	SUPERVISOR	SUPERVISOR	DESCRIPTION	
14	ASSISTANT SUPERVISOR	ASSISTANT SUPERVISOR	DESCRIPTION	
15	TECHNICIAN	TECHNICIAN	DESCRIPTION	
16	HELPER	HELPER	DESCRIPTION	
17	UNDER TRAINING	UNDER TRAINING	DESCRIPTION	
18	User	User	Default user access	
\.


--
-- Data for Name: SalesInvoiceItems; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."SalesInvoiceItems" ("Id", "SalesInvoiceId", "Description", "Hsn", "Quantity", "Rate", "GstPercentage", "Amount", "Total") FROM stdin;
\.


--
-- Data for Name: SalesInvoices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."SalesInvoices" ("Id", "ClientName", "InvoiceNo", "InvoiceDate", "Amount", "GstAmount", "TotalAmount", "PayAmount", "Status", "CreatedAt") FROM stdin;
\.


--
-- Data for Name: SubGsts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."SubGsts" ("Id", "CompanyName", "OfficerName", "Mobile", "GstNumber", "Remarks", "Department", "CreatedAt", "Status", "DepartmentOfficer", "Designation", "EndDate", "StartDate") FROM stdin;
2	DIGITAL NEW ENTERPRISES	Tejesh G	9177010175	27AADCD1234A1Z1	dsvds	IT	2026-05-20 12:06:31.155762	t	IT - IT Support Specialist - Tejesh G	IT Support Specialist	\N	2026-05-01 00:00:00
\.


--
-- Data for Name: SubLocations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."SubLocations" ("Id", "LocationId", "Name", "Description", "CreatedAt") FROM stdin;
1	4	GRSE FOJ	GRSE FOJ	2026-04-02 00:00:00
2	1	INS DEGA BLD	AFLS MUSTERING POINT	2026-03-28 00:00:00
3	3	LION GATE	N/A	2025-12-30 00:00:00
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "Email", "PasswordHash", "FullName", "CreatedAt", "RoleId") FROM stdin;
1	admin@digital.com	Admin@123	System Administrator	2026-05-20 10:46:43.093817	1
2	hr@digital.com	HR@123	HR Manager	2026-05-20 10:46:43.094421	4
3	it@digital.com	IT@123	IT Lead	2026-05-20 10:46:43.094422	5
4	m@gmail.com	1234567890	Amantu	2026-05-21 04:18:22.881305	18
5	t@gmail.com	1234567890	Tejesh G	2026-05-21 12:48:02.75667	18
6	a@gmail.com	1234567890	Arya	2026-05-21 12:57:40.604942	18
7	tejesharyagudla@gmail.com	1234567890	Tejesh Arya Gudla	2026-05-26 05:51:02.534908	18
8				2026-05-26 05:51:20.448177	18
\.


--
-- Data for Name: Wings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Wings" ("Id", "Name", "Description", "Status", "UserCount", "CreatedAt") FROM stdin;
1	ELECTRICAL	DESC	t	0	2025-12-22 05:56:00
2	CIVIL	DEC	t	0	2025-12-22 05:56:00
3	IT	Software development	t	0	2026-05-21 09:13:36.144846
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260507104146_InitialCreate	9.0.1
20260507110328_AddUsersTable	9.0.1
20260508064416_AddCompanyGst	9.0.1
20260508074627_AddDeliveryDetails	9.0.1
20260508075101_AddSubGsts	9.0.1
20260508075426_RedesignSubGst	9.0.1
20260508075826_AddBanks	9.0.1
20260508080147_AddBankDetails	9.0.1
20260508080455_SeedCompanyAndBanks	9.0.1
20260509055307_UpdateEmployeeModel	9.0.1
20260509064606_UpdateBankDetailKey	9.0.1
20260509065424_AddDocumentsTable	9.0.1
20260509070953_AddProjectFilePath	9.0.1
20260509071835_AddQuotations	9.0.1
20260509071958_AddMasters	9.0.1
20260509072443_UpdateQuotationModel	9.0.1
20260509073856_AddPurchaseInvoices	9.0.1
20260509074613_AddPaidAmountToPurchase	9.0.1
20260515091450_AddSalesInvoices	9.0.1
20260515115608_UpdateQuotationWithStatus	9.0.1
20260516071258_AddRoles	9.0.1
20260516074810_AddMasterData	9.0.1
20260516080726_AddPhotoPathToMasterData	9.0.1
20260516080924_AddParentIdToMasterData	9.0.1
20260516082119_AddShortNameToMasterData	9.0.1
20260516082437_AddLocationToMasterData	9.0.1
20260518054748_AddGstStateCodeToMasterData	9.0.1
20260518062217_AddAdditionalInfoToCompanyGst	9.0.1
20260519055952_AddDepartmentOfficerToSubGst	9.0.1
20260519073955_AddDesignationFieldAndTable	9.0.1
20260519080440_AddStartTimeAndEndTimeToDesignationOfficer	9.0.1
20260519082201_AddReferenceKeysToCompanyDeptDesignationEmployee	9.0.1
20260520103624_AddDatesToSubGst	9.0.1
20260521091029_AddWingsTable	9.0.1
20260521091910_AddPostsTable	9.0.1
20260521093731_AddDepartmentFields	9.0.1
20260521101001_AddRoleAssignments	9.0.1
20260521113452_AddLocationDetails	9.0.1
20260521113920_AddSubLocations	9.0.1
20260521122237_AddLocationHeads	9.0.1
20260521122526_AddPostGroupings	9.0.1
20260521123127_AddEmployeeFunds	9.0.1
20260521124100_AddProfileUpdateRequests	9.0.1
20260523063206_AddEmployeeFullFields	9.0.1
20260526105615_AddEmployeeApprovedAt	9.0.1
20260526110149_AddEmployeeApprovedBy	9.0.1
20260527054414_AddEmployeeRequiredRules	9.0.1
20260527055729_UpdateEmployeeRequiredRules	9.0.1
\.


--
-- Name: Banks_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Banks_Id_seq"', 5, false);


--
-- Name: Categories_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Categories_Id_seq"', 1, false);


--
-- Name: DeliveryDetails_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."DeliveryDetails_Id_seq"', 1, true);


--
-- Name: Denominations_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Denominations_Id_seq"', 1, false);


--
-- Name: Departments_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Departments_Id_seq"', 7, true);


--
-- Name: DesignationOfficers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."DesignationOfficers_Id_seq"', 8, true);


--
-- Name: Documents_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Documents_Id_seq"', 1, false);


--
-- Name: EmployeeFamilyMembers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EmployeeFamilyMembers_Id_seq"', 1, true);


--
-- Name: EmployeeFunds_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EmployeeFunds_Id_seq"', 4, false);


--
-- Name: EmployeeRequiredRules_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EmployeeRequiredRules_Id_seq"', 2, false);


--
-- Name: Employees_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Employees_Id_seq"', 107, true);


--
-- Name: HsnCodes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."HsnCodes_Id_seq"', 1, false);


--
-- Name: LocationHeads_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."LocationHeads_Id_seq"', 6, false);


--
-- Name: Locations_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Locations_Id_seq"', 7, true);


--
-- Name: MasterData_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."MasterData_Id_seq"', 42, true);


--
-- Name: PostGroupingItems_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."PostGroupingItems_Id_seq"', 1, false);


--
-- Name: PostGroupings_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."PostGroupings_Id_seq"', 1, false);


--
-- Name: Posts_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Posts_Id_seq"', 5, false);


--
-- Name: ProfileUpdateRequests_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ProfileUpdateRequests_Id_seq"', 4, false);


--
-- Name: PurchaseInvoiceItems_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."PurchaseInvoiceItems_Id_seq"', 1, false);


--
-- Name: PurchaseInvoices_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."PurchaseInvoices_Id_seq"', 1, false);


--
-- Name: QuotationItems_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."QuotationItems_Id_seq"', 1, false);


--
-- Name: Quotations_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Quotations_Id_seq"', 1, false);


--
-- Name: RoleAssignments_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."RoleAssignments_Id_seq"', 5, true);


--
-- Name: Roles_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Roles_Id_seq"', 19, false);


--
-- Name: SalesInvoiceItems_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."SalesInvoiceItems_Id_seq"', 1, false);


--
-- Name: SalesInvoices_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."SalesInvoices_Id_seq"', 1, false);


--
-- Name: SubGsts_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."SubGsts_Id_seq"', 2, true);


--
-- Name: SubLocations_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."SubLocations_Id_seq"', 4, false);


--
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 8, true);


--
-- Name: Wings_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Wings_Id_seq"', 3, true);


--
-- Name: BankDetails PK_BankDetails; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BankDetails"
    ADD CONSTRAINT "PK_BankDetails" PRIMARY KEY ("EmpId");


--
-- Name: Banks PK_Banks; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Banks"
    ADD CONSTRAINT "PK_Banks" PRIMARY KEY ("Id");


--
-- Name: Categories PK_Categories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "PK_Categories" PRIMARY KEY ("Id");


--
-- Name: CompanyGsts PK_CompanyGsts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CompanyGsts"
    ADD CONSTRAINT "PK_CompanyGsts" PRIMARY KEY ("GstNumber");


--
-- Name: DeliveryDetails PK_DeliveryDetails; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DeliveryDetails"
    ADD CONSTRAINT "PK_DeliveryDetails" PRIMARY KEY ("Id");


--
-- Name: Denominations PK_Denominations; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Denominations"
    ADD CONSTRAINT "PK_Denominations" PRIMARY KEY ("Id");


--
-- Name: Departments PK_Departments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Departments"
    ADD CONSTRAINT "PK_Departments" PRIMARY KEY ("Id");


--
-- Name: DesignationOfficers PK_DesignationOfficers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DesignationOfficers"
    ADD CONSTRAINT "PK_DesignationOfficers" PRIMARY KEY ("Id");


--
-- Name: Documents PK_Documents; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Documents"
    ADD CONSTRAINT "PK_Documents" PRIMARY KEY ("Id");


--
-- Name: EmployeeFamilyMembers PK_EmployeeFamilyMembers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EmployeeFamilyMembers"
    ADD CONSTRAINT "PK_EmployeeFamilyMembers" PRIMARY KEY ("Id");


--
-- Name: EmployeeFunds PK_EmployeeFunds; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EmployeeFunds"
    ADD CONSTRAINT "PK_EmployeeFunds" PRIMARY KEY ("Id");


--
-- Name: EmployeeRequiredRules PK_EmployeeRequiredRules; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EmployeeRequiredRules"
    ADD CONSTRAINT "PK_EmployeeRequiredRules" PRIMARY KEY ("Id");


--
-- Name: Employees PK_Employees; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Employees"
    ADD CONSTRAINT "PK_Employees" PRIMARY KEY ("Id");


--
-- Name: HsnCodes PK_HsnCodes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."HsnCodes"
    ADD CONSTRAINT "PK_HsnCodes" PRIMARY KEY ("Id");


--
-- Name: LocationHeads PK_LocationHeads; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LocationHeads"
    ADD CONSTRAINT "PK_LocationHeads" PRIMARY KEY ("Id");


--
-- Name: Locations PK_Locations; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Locations"
    ADD CONSTRAINT "PK_Locations" PRIMARY KEY ("Id");


--
-- Name: MasterData PK_MasterData; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MasterData"
    ADD CONSTRAINT "PK_MasterData" PRIMARY KEY ("Id");


--
-- Name: PostGroupingItems PK_PostGroupingItems; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PostGroupingItems"
    ADD CONSTRAINT "PK_PostGroupingItems" PRIMARY KEY ("Id");


--
-- Name: PostGroupings PK_PostGroupings; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PostGroupings"
    ADD CONSTRAINT "PK_PostGroupings" PRIMARY KEY ("Id");


--
-- Name: Posts PK_Posts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Posts"
    ADD CONSTRAINT "PK_Posts" PRIMARY KEY ("Id");


--
-- Name: ProfileUpdateRequests PK_ProfileUpdateRequests; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProfileUpdateRequests"
    ADD CONSTRAINT "PK_ProfileUpdateRequests" PRIMARY KEY ("Id");


--
-- Name: Projects PK_Projects; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Projects"
    ADD CONSTRAINT "PK_Projects" PRIMARY KEY ("ProjectId");


--
-- Name: PurchaseInvoiceItems PK_PurchaseInvoiceItems; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PurchaseInvoiceItems"
    ADD CONSTRAINT "PK_PurchaseInvoiceItems" PRIMARY KEY ("Id");


--
-- Name: PurchaseInvoices PK_PurchaseInvoices; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PurchaseInvoices"
    ADD CONSTRAINT "PK_PurchaseInvoices" PRIMARY KEY ("Id");


--
-- Name: QuotationItems PK_QuotationItems; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."QuotationItems"
    ADD CONSTRAINT "PK_QuotationItems" PRIMARY KEY ("Id");


--
-- Name: Quotations PK_Quotations; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Quotations"
    ADD CONSTRAINT "PK_Quotations" PRIMARY KEY ("Id");


--
-- Name: RoleAssignments PK_RoleAssignments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."RoleAssignments"
    ADD CONSTRAINT "PK_RoleAssignments" PRIMARY KEY ("Id");


--
-- Name: Roles PK_Roles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Roles"
    ADD CONSTRAINT "PK_Roles" PRIMARY KEY ("Id");


--
-- Name: SalesInvoiceItems PK_SalesInvoiceItems; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SalesInvoiceItems"
    ADD CONSTRAINT "PK_SalesInvoiceItems" PRIMARY KEY ("Id");


--
-- Name: SalesInvoices PK_SalesInvoices; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SalesInvoices"
    ADD CONSTRAINT "PK_SalesInvoices" PRIMARY KEY ("Id");


--
-- Name: SubGsts PK_SubGsts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SubGsts"
    ADD CONSTRAINT "PK_SubGsts" PRIMARY KEY ("Id");


--
-- Name: SubLocations PK_SubLocations; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SubLocations"
    ADD CONSTRAINT "PK_SubLocations" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: Wings PK_Wings; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Wings"
    ADD CONSTRAINT "PK_Wings" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Departments_CompanyGstNumber; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Departments_CompanyGstNumber" ON public."Departments" USING btree ("CompanyGstNumber");


--
-- Name: IX_DesignationOfficers_DepartmentId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_DesignationOfficers_DepartmentId" ON public."DesignationOfficers" USING btree ("DepartmentId");


--
-- Name: IX_EmployeeFamilyMembers_EmployeeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_EmployeeFamilyMembers_EmployeeId" ON public."EmployeeFamilyMembers" USING btree ("EmployeeId");


--
-- Name: IX_EmployeeFunds_EmployeeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_EmployeeFunds_EmployeeId" ON public."EmployeeFunds" USING btree ("EmployeeId");


--
-- Name: IX_Employees_DepartmentId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Employees_DepartmentId" ON public."Employees" USING btree ("DepartmentId");


--
-- Name: IX_Employees_DesignationOfficerId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Employees_DesignationOfficerId" ON public."Employees" USING btree ("DesignationOfficerId");


--
-- Name: IX_Employees_LocationId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Employees_LocationId" ON public."Employees" USING btree ("LocationId");


--
-- Name: IX_LocationHeads_EmployeeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_LocationHeads_EmployeeId" ON public."LocationHeads" USING btree ("EmployeeId");


--
-- Name: IX_LocationHeads_LocationId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_LocationHeads_LocationId" ON public."LocationHeads" USING btree ("LocationId");


--
-- Name: IX_PostGroupingItems_PostGroupingId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PostGroupingItems_PostGroupingId" ON public."PostGroupingItems" USING btree ("PostGroupingId");


--
-- Name: IX_PostGroupingItems_PostId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PostGroupingItems_PostId" ON public."PostGroupingItems" USING btree ("PostId");


--
-- Name: IX_ProfileUpdateRequests_EmployeeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ProfileUpdateRequests_EmployeeId" ON public."ProfileUpdateRequests" USING btree ("EmployeeId");


--
-- Name: IX_PurchaseInvoiceItems_PurchaseInvoiceId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PurchaseInvoiceItems_PurchaseInvoiceId" ON public."PurchaseInvoiceItems" USING btree ("PurchaseInvoiceId");


--
-- Name: IX_QuotationItems_QuotationId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_QuotationItems_QuotationId" ON public."QuotationItems" USING btree ("QuotationId");


--
-- Name: IX_SalesInvoiceItems_SalesInvoiceId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_SalesInvoiceItems_SalesInvoiceId" ON public."SalesInvoiceItems" USING btree ("SalesInvoiceId");


--
-- Name: IX_SubLocations_LocationId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_SubLocations_LocationId" ON public."SubLocations" USING btree ("LocationId");


--
-- Name: IX_Users_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Users_RoleId" ON public."Users" USING btree ("RoleId");


--
-- Name: Departments FK_Departments_CompanyGsts_CompanyGstNumber; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Departments"
    ADD CONSTRAINT "FK_Departments_CompanyGsts_CompanyGstNumber" FOREIGN KEY ("CompanyGstNumber") REFERENCES public."CompanyGsts"("GstNumber");


--
-- Name: DesignationOfficers FK_DesignationOfficers_Departments_DepartmentId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DesignationOfficers"
    ADD CONSTRAINT "FK_DesignationOfficers_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES public."Departments"("Id");


--
-- Name: EmployeeFamilyMembers FK_EmployeeFamilyMembers_Employees_EmployeeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EmployeeFamilyMembers"
    ADD CONSTRAINT "FK_EmployeeFamilyMembers_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES public."Employees"("Id") ON DELETE CASCADE;


--
-- Name: EmployeeFunds FK_EmployeeFunds_Employees_EmployeeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EmployeeFunds"
    ADD CONSTRAINT "FK_EmployeeFunds_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES public."Employees"("Id") ON DELETE CASCADE;


--
-- Name: Employees FK_Employees_Departments_DepartmentId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Employees"
    ADD CONSTRAINT "FK_Employees_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES public."Departments"("Id");


--
-- Name: Employees FK_Employees_DesignationOfficers_DesignationOfficerId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Employees"
    ADD CONSTRAINT "FK_Employees_DesignationOfficers_DesignationOfficerId" FOREIGN KEY ("DesignationOfficerId") REFERENCES public."DesignationOfficers"("Id");


--
-- Name: Employees FK_Employees_Locations_LocationId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Employees"
    ADD CONSTRAINT "FK_Employees_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES public."Locations"("Id");


--
-- Name: LocationHeads FK_LocationHeads_Employees_EmployeeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LocationHeads"
    ADD CONSTRAINT "FK_LocationHeads_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES public."Employees"("Id") ON DELETE CASCADE;


--
-- Name: LocationHeads FK_LocationHeads_Locations_LocationId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LocationHeads"
    ADD CONSTRAINT "FK_LocationHeads_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES public."Locations"("Id") ON DELETE CASCADE;


--
-- Name: PostGroupingItems FK_PostGroupingItems_PostGroupings_PostGroupingId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PostGroupingItems"
    ADD CONSTRAINT "FK_PostGroupingItems_PostGroupings_PostGroupingId" FOREIGN KEY ("PostGroupingId") REFERENCES public."PostGroupings"("Id") ON DELETE CASCADE;


--
-- Name: PostGroupingItems FK_PostGroupingItems_Posts_PostId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PostGroupingItems"
    ADD CONSTRAINT "FK_PostGroupingItems_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES public."Posts"("Id") ON DELETE CASCADE;


--
-- Name: ProfileUpdateRequests FK_ProfileUpdateRequests_Employees_EmployeeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProfileUpdateRequests"
    ADD CONSTRAINT "FK_ProfileUpdateRequests_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES public."Employees"("Id") ON DELETE CASCADE;


--
-- Name: PurchaseInvoiceItems FK_PurchaseInvoiceItems_PurchaseInvoices_PurchaseInvoiceId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PurchaseInvoiceItems"
    ADD CONSTRAINT "FK_PurchaseInvoiceItems_PurchaseInvoices_PurchaseInvoiceId" FOREIGN KEY ("PurchaseInvoiceId") REFERENCES public."PurchaseInvoices"("Id") ON DELETE CASCADE;


--
-- Name: QuotationItems FK_QuotationItems_Quotations_QuotationId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."QuotationItems"
    ADD CONSTRAINT "FK_QuotationItems_Quotations_QuotationId" FOREIGN KEY ("QuotationId") REFERENCES public."Quotations"("Id") ON DELETE CASCADE;


--
-- Name: SalesInvoiceItems FK_SalesInvoiceItems_SalesInvoices_SalesInvoiceId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SalesInvoiceItems"
    ADD CONSTRAINT "FK_SalesInvoiceItems_SalesInvoices_SalesInvoiceId" FOREIGN KEY ("SalesInvoiceId") REFERENCES public."SalesInvoices"("Id") ON DELETE CASCADE;


--
-- Name: SubLocations FK_SubLocations_Locations_LocationId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SubLocations"
    ADD CONSTRAINT "FK_SubLocations_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES public."Locations"("Id") ON DELETE CASCADE;


--
-- Name: Users FK_Users_Roles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."Roles"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict hEGtchCe9tn4Op6yD9EjqfTPcU2jSoTsKQjNGepgfELyc7IfAEQUCmHh2kRijtQ

